// Cambodia Ministry of Education, Youth and Sport (MOEYS) field configuration
// Education Model: KHM_MOEYS
// Native name = lastName + firstName typed in Khmer script
// Latin name = englishLastName + englishFirstName

import type { SystemFieldConfig } from './types';

const GENDER_OPTIONS = [
  { value: 'MALE', label: 'ប្រុស (Male)' },
  { value: 'FEMALE', label: 'ស្រី (Female)' },
];

export const cambodiaMoeysConfig: SystemFieldConfig = {
  student: {
    sections: [
      {
        id: 'personal',
        label: 'Personal Info',
        icon: '👤',
        fields: [
          {
            key: 'lastName',
            label: 'គោត្តនាម (Family Name)',
            type: 'text',
            required: true,
            placeholder: 'ចន',
            span: 2,
          },
          {
            key: 'firstName',
            label: 'នាម (Given Name)',
            type: 'text',
            required: true,
            placeholder: 'មុន្នីរ័ត្ន',
            span: 2,
          },
          {
            key: 'englishLastName',
            label: 'Last Name (Latin)',
            type: 'text',
            required: false,
            placeholder: 'Chan',
            span: 2,
          },
          {
            key: 'englishFirstName',
            label: 'First Name (Latin)',
            type: 'text',
            required: false,
            placeholder: 'Monyrath',
            span: 2,
          },
          {
            key: 'gender',
            label: 'ភេទ (Gender)',
            type: 'select',
            required: true,
            options: GENDER_OPTIONS,
            span: 2,
          },
          {
            key: 'dateOfBirth',
            label: 'ថ្ងៃខែឆ្នាំកំណើត (Date of Birth)',
            type: 'date',
            required: true,
            span: 2,
          },
          {
            key: 'placeOfBirth',
            label: 'ទីកន្លែងកំណើត (Place of Birth)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ភ្នំពេញ',
            span: 1,
          },
          {
            key: 'currentAddress',
            label: 'អាសយដ្ឋានបច្ចុប្បន្ន (Current Address)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ផ្ទះលេខ... ភ្នំពេញ',
            span: 1,
          },
          {
            key: 'phoneNumber',
            label: 'លេខទូរសព្ទ (Phone)',
            type: 'tel',
            placeholder: '+855 12 345 678',
            span: 2,
          },
          {
            key: 'email',
            label: 'អ៊ីមែល (Email)',
            type: 'email',
            placeholder: 'student@school.edu.kh',
            span: 2,
          },
        ],
      },
      {
        id: 'family',
        label: 'Parent & Family',
        icon: '👨‍👩‍👧',
        fields: [
          {
            key: 'fatherName',
            label: 'ឈ្មោះឪពុក (Father\'s Name)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ចន សុភ័ក្ត្រ',
            span: 2,
          },
          {
            key: 'motherName',
            label: 'ឈ្មោះម្ដាយ (Mother\'s Name)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ម៉ម សុភា',
            span: 2,
          },
          {
            key: 'parentPhone',
            label: 'លេខទូរសព្ទឪពុកម្ដាយ (Parent Phone)',
            type: 'tel',
            isCustomField: true,
            placeholder: '+855 12 345 678',
            span: 2,
          },
          {
            key: 'parentOccupation',
            label: 'មុខរបរឪពុកម្ដាយ (Parent Occupation)',
            type: 'text',
            isCustomField: true,
            placeholder: 'កសិករ',
            span: 2,
          },
        ],
      },
      {
        id: 'academic',
        label: 'Academic History',
        icon: '📚',
        fields: [
          {
            key: 'previousSchool',
            label: 'សាលារៀនមុន (Previous School)',
            type: 'text',
            isCustomField: true,
            placeholder: 'អនុវិទ្យាល័យ...',
            span: 2,
          },
          {
            key: 'previousGrade',
            label: 'ថ្នាក់ចុងក្រោយ (Previous Grade)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ទី ៦',
            span: 2,
          },
          {
            key: 'repeatingGrade',
            label: 'ថ្នាក់ដែលរៀនម្ដងទៀត (Repeating Grade)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ទី ៧',
            span: 2,
          },
          {
            key: 'transferredFrom',
            label: 'ផ្ទេរពីសាលា (Transferred From)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ខេត្ត/ក្រុង',
            span: 2,
          },
          {
            key: 'remarks',
            label: 'កំណត់ចំណាំ (Remarks)',
            type: 'textarea',
            isCustomField: true,
            placeholder: 'កំណត់ចំណាំ...',
            span: 1,
          },
        ],
      },
      {
        id: 'exams',
        label: 'Exam Records',
        icon: '📝',
        fields: [
          // Grade 9
          {
            key: 'grade9ExamSession',
            label: 'សម័យប្រឡង ទី ៩ (Grade 9 Exam Session)',
            type: 'text',
            isCustomField: true,
            placeholder: '2024',
            span: 2,
          },
          {
            key: 'grade9ExamCenter',
            label: 'មជ្ឈមណ្ឌលប្រឡង (Exam Center)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ភ្នំពេញ',
            span: 2,
          },
          {
            key: 'grade9ExamRoom',
            label: 'បន្ទប់ប្រឡង (Exam Room)',
            type: 'text',
            isCustomField: true,
            placeholder: '01',
            span: 2,
          },
          {
            key: 'grade9ExamDesk',
            label: 'លេខតុ (Desk No.)',
            type: 'text',
            isCustomField: true,
            placeholder: '001',
            span: 2,
          },
          {
            key: 'grade9PassStatus',
            label: 'លទ្ធផល ទី ៩ (Grade 9 Result)',
            type: 'select',
            isCustomField: true,
            options: [
              { value: '', label: 'មិនទាន់ (Not yet)' },
              { value: 'PASS', label: 'បាន (Pass)' },
              { value: 'FAIL', label: 'មិនបាន (Fail)' },
            ],
            span: 1,
          },
          // Grade 12
          {
            key: 'grade12ExamSession',
            label: 'សម័យប្រឡង ទី ១២ (Grade 12 Exam Session)',
            type: 'text',
            isCustomField: true,
            placeholder: '2025',
            span: 2,
          },
          {
            key: 'grade12ExamCenter',
            label: 'មជ្ឈមណ្ឌលប្រឡង ទី ១២ (G12 Exam Center)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ភ្នំពេញ',
            span: 2,
          },
          {
            key: 'grade12ExamRoom',
            label: 'បន្ទប់ប្រឡង ទី ១២ (G12 Room)',
            type: 'text',
            isCustomField: true,
            placeholder: '01',
            span: 2,
          },
          {
            key: 'grade12ExamDesk',
            label: 'លេខតុ ទី ១២ (G12 Desk No.)',
            type: 'text',
            isCustomField: true,
            placeholder: '001',
            span: 2,
          },
          {
            key: 'grade12Track',
            label: 'ផ្នែក ទី ១២ (G12 Track)',
            type: 'select',
            isCustomField: true,
            options: [
              { value: '', label: 'មិនទាន់ (Not yet)' },
              { value: 'SCIENCE', label: 'វិទ្យាសាស្ត្រ (Science)' },
              { value: 'SOCIAL', label: 'សង្គមវិទ្យា (Social)' },
            ],
            span: 2,
          },
          {
            key: 'grade12PassStatus',
            label: 'លទ្ធផល ទី ១២ (Grade 12 Result)',
            type: 'select',
            isCustomField: true,
            options: [
              { value: '', label: 'មិនទាន់ (Not yet)' },
              { value: 'PASS', label: 'បាន (Pass)' },
              { value: 'FAIL', label: 'មិនបាន (Fail)' },
            ],
            span: 1,
          },
        ],
      },
    ],
  },

  teacher: {
    sections: [
      {
        id: 'personal',
        label: 'Personal Info',
        icon: '👤',
        fields: [
          {
            key: 'lastName',
            label: 'គោត្តនាម (Family Name)',
            type: 'text',
            required: true,
            placeholder: 'សុខ',
            span: 2,
          },
          {
            key: 'firstName',
            label: 'នាម (Given Name)',
            type: 'text',
            required: true,
            placeholder: 'ដារ៉ា',
            span: 2,
          },
          {
            key: 'englishLastName',
            label: 'Last Name (Latin)',
            type: 'text',
            placeholder: 'Sok',
            span: 2,
          },
          {
            key: 'englishFirstName',
            label: 'First Name (Latin)',
            type: 'text',
            placeholder: 'Dara',
            span: 2,
          },
          {
            key: 'gender',
            label: 'ភេទ (Gender)',
            type: 'select',
            required: true,
            options: GENDER_OPTIONS,
            span: 2,
          },
          {
            key: 'dateOfBirth',
            label: 'ថ្ងៃខែឆ្នាំកំណើត (Date of Birth)',
            type: 'date',
            required: true,
            span: 2,
          },
          {
            key: 'idCard',
            label: 'លេខអត្តសញ្ញាណប័ណ្ណ (ID Card No.)',
            type: 'text',
            isCustomField: true,
            placeholder: '012345678',
            span: 2,
          },
          {
            key: 'passport',
            label: 'លេខលិខិតឆ្លងដែន (Passport No.)',
            type: 'text',
            isCustomField: true,
            placeholder: 'A0123456',
            span: 2,
          },
          {
            key: 'nationality',
            label: 'សញ្ជាតិ (Nationality)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ខ្មែរ',
            span: 2,
          },
        ],
      },
      {
        id: 'contact',
        label: 'Contact & Address',
        icon: '📞',
        fields: [
          {
            key: 'phoneNumber',
            label: 'លេខទូរសព្ទ (Phone)',
            type: 'tel',
            required: true,
            placeholder: '+855 12 345 678',
            span: 2,
          },
          {
            key: 'email',
            label: 'អ៊ីមែល (Email)',
            type: 'email',
            placeholder: 'teacher@school.edu.kh',
            span: 2,
          },
          {
            key: 'address',
            label: 'អាសយដ្ឋាន (Address)',
            type: 'text',
            placeholder: 'ភ្នំពេញ',
            span: 1,
          },
          {
            key: 'emergencyContact',
            label: 'ទំនាក់ទំនងបន្ទាន់ (Emergency Contact)',
            type: 'text',
            isCustomField: true,
            placeholder: 'ឈ្មោះ',
            span: 2,
          },
          {
            key: 'emergencyPhone',
            label: 'ទូរសព្ទបន្ទាន់ (Emergency Phone)',
            type: 'tel',
            isCustomField: true,
            placeholder: '+855 12 345 678',
            span: 2,
          },
        ],
      },
      {
        id: 'employment',
        label: 'Employment',
        icon: '🏫',
        fields: [
          {
            key: 'hireDate',
            label: 'កាលបរិច្ឆេទចូលបម្រើការ (Hire Date)',
            type: 'date',
            required: true,
            span: 2,
          },
          {
            key: 'position',
            label: 'មុខតំណែង (Position)',
            type: 'text',
            isCustomField: true,
            placeholder: 'គ្រូបង្រៀន',
            span: 2,
          },
          {
            key: 'workingLevel',
            label: 'កម្រិតបំពេញការងារ (Working Level)',
            type: 'select',
            isCustomField: true,
            options: [
              { value: '', label: 'ជ្រើសរើស...' },
              { value: 'FULL_TIME', label: 'ពេញម៉ោង (Full Time)' },
              { value: 'PART_TIME', label: 'កន្លះម៉ោង (Part Time)' },
              { value: 'CONTRACT', label: 'កិច្ចសន្យា (Contract)' },
            ],
            span: 2,
          },
          {
            key: 'salaryRange',
            label: 'ចន្លោះប្រាក់ខែ (Salary Range)',
            type: 'text',
            isCustomField: true,
            placeholder: '300-500 USD',
            span: 2,
          },
        ],
      },
      {
        id: 'qualifications',
        label: 'Qualifications',
        icon: '🎓',
        fields: [
          {
            key: 'degree',
            label: 'សញ្ញាបត្រ (Degree)',
            type: 'select',
            isCustomField: true,
            options: [
              { value: '', label: 'ជ្រើសរើស...' },
              { value: 'HIGH_SCHOOL', label: 'បញ្ចប់ ទ.១២ (High School)' },
              { value: 'ASSOCIATE', label: 'អនុបណ្ឌិត (Associate)' },
              { value: 'BACHELOR', label: 'បរិញ្ញាបត្រ (Bachelor)' },
              { value: 'MASTER', label: 'អនុបណ្ឌិតលើ (Master)' },
              { value: 'PHD', label: 'បណ្ឌិត (PhD)' },
            ],
            span: 1,
          },
          {
            key: 'major1',
            label: 'ឯកទេសទី ១ (Major 1)',
            type: 'text',
            isCustomField: true,
            placeholder: 'គណិតវិទ្យា',
            span: 2,
          },
          {
            key: 'major2',
            label: 'ឯកទេសទី ២ (Major 2)',
            type: 'text',
            isCustomField: true,
            placeholder: 'រូបវិទ្យា',
            span: 2,
          },
        ],
      },
    ],
  },
};
