// Default / International field configuration
// Used when educationModel is not KHM_MOEYS or is unrecognized.

import type { SystemFieldConfig } from './types';

const GENDER_OPTIONS = [
  { value: 'MALE', label: 'Male' },
  { value: 'FEMALE', label: 'Female' },
];

export const defaultConfig: SystemFieldConfig = {
  student: {
    sections: [
      {
        id: 'personal',
        label: 'Personal Info',
        icon: '👤',
        fields: [
          {
            key: 'lastName',
            label: 'Last Name',
            type: 'text',
            required: true,
            placeholder: 'Smith',
            span: 2,
          },
          {
            key: 'firstName',
            label: 'First Name',
            type: 'text',
            required: true,
            placeholder: 'John',
            span: 2,
          },
          {
            key: 'englishLastName',
            label: 'Last Name (International)',
            type: 'text',
            placeholder: 'Smith',
            span: 2,
          },
          {
            key: 'englishFirstName',
            label: 'First Name (International)',
            type: 'text',
            placeholder: 'John',
            span: 2,
          },
          {
            key: 'gender',
            label: 'Gender',
            type: 'select',
            required: true,
            options: GENDER_OPTIONS,
            span: 2,
          },
          {
            key: 'dateOfBirth',
            label: 'Date of Birth',
            type: 'date',
            required: true,
            span: 2,
          },
          {
            key: 'placeOfBirth',
            label: 'Place of Birth',
            type: 'text',
            isCustomField: true,
            placeholder: 'City, Country',
            span: 2,
          },
          {
            key: 'currentAddress',
            label: 'Current Address',
            type: 'text',
            isCustomField: true,
            placeholder: '123 Main St, City',
            span: 1,
          },
          {
            key: 'phoneNumber',
            label: 'Phone Number',
            type: 'tel',
            placeholder: '+1 234 567 8900',
            span: 2,
          },
          {
            key: 'email',
            label: 'Email',
            type: 'email',
            placeholder: 'student@school.edu',
            span: 2,
          },
        ],
      },
      {
        id: 'family',
        label: 'Family Info',
        icon: '👨‍👩‍👧',
        fields: [
          {
            key: 'fatherName',
            label: "Father's Name",
            type: 'text',
            isCustomField: true,
            placeholder: 'Full name',
            span: 2,
          },
          {
            key: 'motherName',
            label: "Mother's Name",
            type: 'text',
            isCustomField: true,
            placeholder: 'Full name',
            span: 2,
          },
          {
            key: 'parentPhone',
            label: 'Parent / Guardian Phone',
            type: 'tel',
            isCustomField: true,
            placeholder: '+1 234 567 8900',
            span: 2,
          },
          {
            key: 'parentOccupation',
            label: 'Parent / Guardian Occupation',
            type: 'text',
            isCustomField: true,
            placeholder: 'Occupation',
            span: 2,
          },
          {
            key: 'remarks',
            label: 'Remarks',
            type: 'textarea',
            isCustomField: true,
            placeholder: 'Any additional notes...',
            span: 1,
          },
        ],
      },
    ],
  },

  teacher: {
    sections: [
      {
        id: 'personal',
        label: 'Personal Info',
        icon: '👤',
        fields: [
          {
            key: 'lastName',
            label: 'Last Name',
            type: 'text',
            required: true,
            placeholder: 'Smith',
            span: 2,
          },
          {
            key: 'firstName',
            label: 'First Name',
            type: 'text',
            required: true,
            placeholder: 'John',
            span: 2,
          },
          {
            key: 'englishLastName',
            label: 'Last Name (International)',
            type: 'text',
            placeholder: 'Smith',
            span: 2,
          },
          {
            key: 'englishFirstName',
            label: 'First Name (International)',
            type: 'text',
            placeholder: 'John',
            span: 2,
          },
          {
            key: 'gender',
            label: 'Gender',
            type: 'select',
            required: true,
            options: GENDER_OPTIONS,
            span: 2,
          },
          {
            key: 'dateOfBirth',
            label: 'Date of Birth',
            type: 'date',
            required: true,
            span: 2,
          },
          {
            key: 'nationality',
            label: 'Nationality',
            type: 'text',
            isCustomField: true,
            placeholder: 'e.g. American',
            span: 2,
          },
        ],
      },
      {
        id: 'contact',
        label: 'Contact & Address',
        icon: '📞',
        fields: [
          {
            key: 'phoneNumber',
            label: 'Phone Number',
            type: 'tel',
            required: true,
            placeholder: '+1 234 567 8900',
            span: 2,
          },
          {
            key: 'email',
            label: 'Email',
            type: 'email',
            placeholder: 'teacher@school.edu',
            span: 2,
          },
          {
            key: 'address',
            label: 'Address',
            type: 'text',
            placeholder: '123 Main St, City',
            span: 1,
          },
          {
            key: 'emergencyContact',
            label: 'Emergency Contact Name',
            type: 'text',
            isCustomField: true,
            placeholder: 'Full name',
            span: 2,
          },
          {
            key: 'emergencyPhone',
            label: 'Emergency Phone',
            type: 'tel',
            isCustomField: true,
            placeholder: '+1 234 567 8900',
            span: 2,
          },
        ],
      },
      {
        id: 'employment',
        label: 'Employment',
        icon: '🏫',
        fields: [
          {
            key: 'hireDate',
            label: 'Hire Date',
            type: 'date',
            required: true,
            span: 2,
          },
          {
            key: 'position',
            label: 'Position / Title',
            type: 'text',
            isCustomField: true,
            placeholder: 'Math Teacher',
            span: 2,
          },
          {
            key: 'degree',
            label: 'Highest Degree',
            type: 'select',
            isCustomField: true,
            options: [
              { value: '', label: 'Select...' },
              { value: 'HIGH_SCHOOL', label: 'High School' },
              { value: 'ASSOCIATE', label: 'Associate' },
              { value: 'BACHELOR', label: "Bachelor's" },
              { value: 'MASTER', label: "Master's" },
              { value: 'PHD', label: 'PhD' },
            ],
            span: 2,
          },
          {
            key: 'major1',
            label: 'Major / Subject Area',
            type: 'text',
            isCustomField: true,
            placeholder: 'Mathematics',
            span: 2,
          },
        ],
      },
    ],
  },
};
