#!/bin/bash
# Write gitignored dev env files for project stunity-dev (ykvqgyrwizqjjzfuitto).
# Does NOT commit secrets. Re-run only when password or keys rotate.
#
# Usage:
#   ./scripts/setup-dev-supabase-env.sh
#   source scripts/activate-dev-database.sh && ./quick-start-lite.sh

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REF="${SUPABASE_DEV_PROJECT_REF:-ykvqgyrwizqjjzfuitto}"
POOLER_HOST="${SUPABASE_DEV_POOLER_HOST:-aws-1-ap-southeast-1.pooler.supabase.com}"
DB_PASSWORD="${SUPABASE_DEV_DB_PASSWORD:-}"

if [ -z "$DB_PASSWORD" ]; then
  echo "Set SUPABASE_DEV_DB_PASSWORD (database password from Supabase dashboard), then re-run."
  echo "Example:"
  echo "  SUPABASE_DEV_DB_PASSWORD='your-password' ./scripts/setup-dev-supabase-env.sh"
  exit 1
fi

PASS_ENC="$(node -e "console.log(encodeURIComponent(process.argv[1]))" "$DB_PASSWORD")"
SUPABASE_URL="${SUPABASE_DEV_URL:-https://${REF}.supabase.co}"
ANON_OR_PUBLISHABLE="${SUPABASE_DEV_ANON_KEY:-${SUPABASE_DEV_PUBLISHABLE_KEY:-}}"

if [ -z "$ANON_OR_PUBLISHABLE" ]; then
  echo "Set SUPABASE_DEV_ANON_KEY or SUPABASE_DEV_PUBLISHABLE_KEY (Project Settings → API)."
  exit 1
fi

DATABASE_URL="postgresql://postgres.${REF}:${PASS_ENC}@${POOLER_HOST}:6543/postgres?pgbouncer=true"
DIRECT_URL="postgresql://postgres.${REF}:${PASS_ENC}@${POOLER_HOST}:5432/postgres"

ROOT_DEV="$PROJECT_DIR/.env.development.local"
MOBILE_DEV="$PROJECT_DIR/apps/mobile/.env.local"

cat > "$ROOT_DEV" <<EOF
# AUTO-GENERATED by scripts/setup-dev-supabase-env.sh — gitignored
# Dev project: stunity-dev (${REF})

STUNITY_USE_DEV_DB=1
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${ANON_OR_PUBLISHABLE}

DATABASE_URL=${DATABASE_URL}
DIRECT_URL=${DIRECT_URL}

PRISMA_CONNECTION_LIMIT=2
PRISMA_POOL_TIMEOUT=10
DISABLE_DB_KEEPALIVE=1
SKIP_DB_MIGRATE=1
SKIP_MESSAGING_SERVICE=1
EOF

cat > "$MOBILE_DEV" <<EOF
# AUTO-GENERATED — gitignored. Dev Realtime only.
EXPO_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
EXPO_PUBLIC_SUPABASE_ANON_KEY=${ANON_OR_PUBLISHABLE}
EXPO_PUBLIC_API_HOST=localhost
EOF

chmod 600 "$ROOT_DEV" "$MOBILE_DEV" 2>/dev/null || true

echo "✅ Wrote $ROOT_DEV"
echo "✅ Wrote $MOBILE_DEV"
echo ""
echo "Next:"
echo "  source scripts/activate-dev-database.sh"
echo "  ./scripts/bootstrap-dev-database.sh   # first time: sync schema to empty dev DB"
echo "  ./quick-start-lite.sh"
echo "  cd apps/mobile && npx expo start --clear"
