const {
  AndroidConfig,
  withAndroidManifest,
  withDangerousMod,
  withInfoPlist,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Release-oriented TLS public-key pinning for Stunity API hosts.
 *
 * - Android: Network Security Config pin-set (OkHttp / platform stack)
 * - iOS: NSAppTransportSecurity NSPinnedDomains (NSPinnedCAIdentities)
 *
 * Enabled for production EAS builds by default, or when EXPO_PUBLIC_SSL_PINNING=true.
 * Dev LAN cleartext (http://IP:port) is unaffected — pins only apply to listed HTTPS hosts.
 */

function loadPinConfig(projectRoot) {
  const pinPath = path.join(projectRoot, 'ssl-pins.json');
  const raw = JSON.parse(fs.readFileSync(pinPath, 'utf8'));
  if (!Array.isArray(raw.hosts) || !Array.isArray(raw.pins) || raw.pins.length < 2) {
    throw new Error('[withSslPinning] ssl-pins.json must define hosts[] and at least 2 pins[]');
  }
  return raw;
}

function shouldEnable(options = {}) {
  if (options.enabled === true) return true;
  if (options.enabled === false) return false;
  if (process.env.EXPO_PUBLIC_SSL_PINNING === 'true') return true;
  if (process.env.EXPO_PUBLIC_SSL_PINNING === 'false') return false;
  // EAS production profile (and production-like APP_ENV)
  if (process.env.EAS_BUILD_PROFILE === 'production') return true;
  if (process.env.EXPO_PUBLIC_APP_ENV === 'production') return true;
  return false;
}

function buildNetworkSecurityConfigXml(pinConfig) {
  const pinLines = pinConfig.pins
    .map((p) => `            <pin digest="SHA-256">${p.spkiSha256}</pin>`)
    .join('\n');
  const domainBlocks = pinConfig.hosts
    .map(
      (host) => `        <domain includeSubdomains="false">${host}</domain>`,
    )
    .join('\n');

  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by withSslPinning — do not edit by hand -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="false">
${domainBlocks}
        <pin-set expiration="${pinConfig.androidPinSetExpiration || '2027-12-31'}">
${pinLines}
        </pin-set>
    </domain-config>
    <!-- Keep debug cleartext for LAN/dev hosts outside the pin-set -->
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
            <certificates src="user" />
        </trust-anchors>
    </base-config>
</network-security-config>
`;
}

function withAndroidSslPinning(config, pinConfig) {
  config = withDangerousMod(config, [
    'android',
    async (cfg) => {
      const xmlDir = path.join(
        cfg.modRequest.platformProjectRoot,
        'app',
        'src',
        'main',
        'res',
        'xml',
      );
      fs.mkdirSync(xmlDir, { recursive: true });
      fs.writeFileSync(
        path.join(xmlDir, 'network_security_config.xml'),
        buildNetworkSecurityConfigXml(pinConfig),
        'utf8',
      );
      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:networkSecurityConfig'] = '@xml/network_security_config';
    return cfg;
  });
}

function withIosSslPinning(config, pinConfig) {
  return withInfoPlist(config, (cfg) => {
    const pinnedDomains = {};
    for (const host of pinConfig.hosts) {
      pinnedDomains[host] = {
        NSIncludesSubdomains: false,
        NSPinnedCAIdentities: pinConfig.pins.map((p) => ({
          'SPKI-SHA256-BASE64': p.spkiSha256,
        })),
      };
    }

    const ats = cfg.modResults.NSAppTransportSecurity || {};
    cfg.modResults.NSAppTransportSecurity = {
      ...ats,
      NSPinnedDomains: {
        ...(ats.NSPinnedDomains || {}),
        ...pinnedDomains,
      },
    };
    return cfg;
  });
}

function withSslPinning(config, options = {}) {
  if (!shouldEnable(options)) {
    console.log(
      '[withSslPinning] skipped (enable via EAS production profile or EXPO_PUBLIC_SSL_PINNING=true)',
    );
    return config;
  }

  const projectRoot = config._internal?.projectRoot || process.cwd();
  const pinConfig = loadPinConfig(projectRoot);
  console.log(
    `[withSslPinning] enabling pins for ${pinConfig.hosts.join(', ')}`,
  );

  config = withAndroidSslPinning(config, pinConfig);
  config = withIosSslPinning(config, pinConfig);
  return config;
}

module.exports = withSslPinning;
