ALTER TYPE "CourseItemType" ADD VALUE IF NOT EXISTS 'DOCUMENT';
ALTER TYPE "CourseItemType" ADD VALUE IF NOT EXISTS 'PDF';
ALTER TYPE "CourseItemType" ADD VALUE IF NOT EXISTS 'FILE';
ALTER TYPE "CourseItemType" ADD VALUE IF NOT EXISTS 'IMAGE';
